name: SiT
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python >= 3.10
  - pytorch >= 2.4.0
  - torchvision
  - pytorch-cuda=12.4
  - pip
  - pip:
    - timm
    - diffusers
    - accelerate
    - torchdiffeq
    - wandb
    - transformers
    - mkl <2025
    - mkl-include <2025
